### ISSUE TITLE
Errors when Installed from NPM 

### ISSUE THREAD

**Issue by dcpesses** [castlabs/downstream_electron#84]
I followed the directions from https://castlabs.github.io/downstream_electron/ on installing the DOWNstream component via NPM, but whenever I require it in the main process, I receive the following error for v0.3.3:

```
App threw an error during load
Error: Cannot find module './api/index'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/dpesses/Projects/OfflineDRMPlayback/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dpesses/Projects/OfflineDRMPlayback/node_modules/downstream-electron/index.js:4:28)
    at Object.<anonymous> (/Users/dpesses/Projects/OfflineDRMPlayback/node_modules/downstream-electron/index.js:46:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

Is it possible that only the directory `/api` should be built when it's included as a module instead of the entire project?

EDIT: It appears the error was introduced in v0.3.0, as this _will_ load properly if I use v0.2.8. (FYI, v0.2.9 will throw an error if `get-folder-size` was not previously installed.

**Comment by mackode** [comment]
Thank you for you contribution. This issue should be fixed in v0.3.5.
